### PR TITLE
Updating contributor guide documentation

### PR DESCRIPTION
**Pull request by hCraker**
This PR addressed the following:
- [x] changing references to the `master` branch to say `main` branch
- [x] fixing a few typos in section 4.2.2
- [x] updating the documentation example in 4.2.2 to match the new standard seen in geocat-comp

This is still a draft until I am able to generate the webpage locally to check for any formatting errors.

### CODE REVIEW

**Comment by hCraker** [comment]
I have generated the documentation locally, and it appears to be correct. If anyone wants to do the same, you'll need to:
- have the most recent version of Docker running
- have Ruby installed.
- install jekyll using Ruby
- make sure you're on the typo-fix branch in your local
- from the root directory of the repository, run `docker-compose up --build`
- paste the server address into your browser

@anissa111 I think these are all the steps we determined were necessary. Please let me know if I missed something

**Comment by anissa111** [comment]
@hCraker my list of steps looks like the following:

1. make sure docker is up to date and running
3. edit the `_config.yml` file to have the following exclude block:
```
Make sure _config.yml is like the following:

exclude:
    - docker-compose.yml
    - Dockerfile
    - Rakefile
    - README.md
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
```
4. Add the following lines to the bottom of the Gemfile (possibly should be a future PR)
```
# add webrick for workaround about bundler not finding jekyll
gem "webrick"
```
5. Be on the intended branch
6. from the root directory of the repository, run `docker-compose up --build`. This should print out a bunch of stuff and then hang, showing a local address as one of the last things printed to terminal
7. paste the server address into your browser

I actually do not think you have to install ruby separately or install jekyll because that should be (??) taken care of by docker.

It would be interesting to see if somebody other than us could follow these steps successfully and tell us the minimum steps they needed to get it to work.

**Comment by hCraker** [comment]
I forgot about the config file. I'll take your instructions and put them in our internal GeoCAT guide. We can edit them once somebody gives this a shot. Thanks!

**Comment by anissa111** [comment]
Yeah! I am also unsure about whether doing the `bundle install` step is necessary? That might need to be included in future versions of those instructions.

Okay I'll actually do the review part of this PR now.

**Review by anissa111 — APPROVED** [review]
Looks good!

**Comment by hCraker** [comment]
Thanks for looking at this. Do you know if I need to deploy this branch before merging? Or am I good to merge and deploy on main?

**Comment by anissa111** [comment]
I think all you need to do is to merge changes to the gh-pages branch and an action will automatically do everything from there. The site is run from gh-pages, not main.

Edit: I'm going to push the button. Hope I'm right!

**Comment by anissa111** [comment]
Looks like it worked! Changes are live at https://geocat.ucar.edu/

**Pull request merged**
